name: pfe_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0
  lucide_icons: 0.257.0
  image_picker: ^1.0.4
  ikchatbot: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_screenutil: ^5.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/tesla.png
    - assets/BMW M4.png
    - assets/AUDI RS5.png
    - assets/chorliya.png
    - assets/image33.png
    - assets/image22.png
    - assets/image11.png
    - assets/beepbeep.png
    - assets/welcome.png
    - assets/tesla Model S.png
    - assets/Porsche 911.png
    - assets/Mercedes G63.png
    - assets/Audi RS7.png
    - assets/bmw s2.png
    - assets/C63 AMG.png
    - assets/pofile-photo.png

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF
        
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
          weight: 500
          
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 700
          
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
          style: italic
          
        - asset: assets/fonts/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
          
        - asset: assets/fonts/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          
        - asset: assets/fonts/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 600
          style: italic
          
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          style: italic
          
        - asset: assets/fonts/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
        

  
